alert("I am Muhammad Ali Siddiqui (alideveloper15).")
alert("I am 14 years old, studying in 9th class.")
alert("Error! Please enter a valid password.")
alert("Welcome to Js Land...")
alert("Happy Coding!")
alert("Hello... I can run JS through my web browser's console")